apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: olm-update-sentinel-role
rules:
  - apiGroups: ["operators.coreos.com"]
    resources: ["subscriptions", "clusterserviceversions", "packagemanifests"]
    verbs: ["get", "list", "watch"]
