apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: olm-update-sentinel
  namespace: olm-update-sentinel-system
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  endpoints:
    - port: metrics
      interval: 60s
